### ISSUE TITLE
Set up your work environment for future tasks

### ISSUE THREAD

**Issue by Alejandro-HUB** [Alejandro-HUB/Muszilla#1]
1. Connect to the AWS RDS Instance (Database)

- Download Microsoft SQL Server
- Enter the credentials that I sent through Discord.

2. Accept invitation on Azure Portal to contribute to the storage container
![image](https://user-images.githubusercontent.com/58063303/167740185-f7f5e827-9a52-4b94-9e99-f1b4f4f43cbb.png)

**Comment by Oozaru71** [comment]
Completed!
