### ISSUE TITLE
Link the Drop-Down Menu Pages to the Homepage

### ISSUE THREAD

**Issue by Alejandro-HUB** [Alejandro-HUB/Muszilla#9]
### Look at this link for reference on how the template is linked together and how it should look: [Template](http://preview.themeforest.net/item/musik-music-web-application-template/full_screen_preview/7831557?_ga=2.165405687.916100062.1655351100-709606352.1645591935)

We will be linking all the pages in the drop-down menu together and turning the .html pages into .cshtml so that they can be used in our app:

![image](https://user-images.githubusercontent.com/58063303/173988259-0d5e75ba-6b48-4bf4-aaab-148ea1679c30.png)

If you need help regarding the UI look at the documentation for the template. It should be under docs.html:

![image](https://user-images.githubusercontent.com/58063303/173987941-08c89ca6-fe0c-4327-8e2b-f8fda86f5ef0.png)

### 1 Finish up the previous task

- You added functionality to the log-out button, but you missed the second log-out button here: 

![image](https://user-images.githubusercontent.com/58063303/173984865-fcebb6cf-45ca-4740-89af-e2da947a9424.png)

- You did fix the logo's size issue but you left the styling in the code. A production-ready software includes the CSS in a separate file and uses CSS classes to style objects.

![image](https://user-images.githubusercontent.com/58063303/173985481-077c962b-db61-4e23-b5f9-035608d41979.png)

### 2 Try to move all folders out of Home. 

- Try to figure out how to have all views in different folders because we don't want every single page under home. Furthermore, I do see 2 Signup pages, let's try to keep the code clean 👍 

![image](https://user-images.githubusercontent.com/58063303/173985809-061427b7-85a5-4d74-a791-ecb17dd67db0.png)

### 3 Link the Profile page to the home page. 

- In the two places marked in the picture, when I click profile I should be redirected to the profile page.

![image](https://user-images.githubusercontent.com/58063303/173985958-6e75f89f-632d-427e-bb42-48a0c19a98c6.png)

- The profile should look like this and it is named profile.html:

![image](https://user-images.githubusercontent.com/58063303/173986290-d67f3932-d340-4e97-a891-26829eae7701.png)

-  Don't worry too much about the functionalities that we do not have, but try to at least have the profile picture and name where it belongs. 

### 4 Settings Page

- Currently, the app does not have a settings page, therefore, you need to build it. We already have all the logic for it done on Muszilla, so you just need to link the back end to your page once you finish it.
- Tip: You have all the assets you need:
- You even have a blank page with all the page's styling already made for you. Just use the blank page as a base and use the assets to put a settings page together.

Assets:
![image](https://user-images.githubusercontent.com/58063303/173987119-14a7e9ed-9651-42f4-a7b7-da9df2d46fb3.png)

Blank page:
It is called Blank.html
![image](https://user-images.githubusercontent.com/58063303/173987372-2b9079a0-7c3b-4c6d-95e0-0b23e2687e56.png)

Make sure that when you switch in between pages the username and profile photo still show here:

![image](https://user-images.githubusercontent.com/58063303/173987457-60b93f8a-354c-4bf7-9c0e-97fff0d297bb.png)

If you remember, this is the settings page in Muszilla and all the backend logic is already done for it:

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/58063303/173989296-f3f54480-c399-470f-b60b-7b8cc4016f52.png">

### 5 Notifications Page

- Again, there is nothing really made for notifications but use all the assets available brought by the template to build something. I'm not really sure what would go here but at least come up with a page 👍 

- Again, you have a lot of pages, assets, layouts, etc... with styling already applied to match the template. These are available for you so no need to reinvent the wheel:

![image](https://user-images.githubusercontent.com/58063303/173987760-839cc3c7-d723-4b22-8aa9-462444d5ac67.png)

### 6 Help page

- If you see in the link above, the Help button redirects you to docs.html which is currently the documentation for the template.
-  What you can add here is perhaps the name of the app and who made it. Perhaps even a short description regarding the app. I already listed a description in the Github page but feel free to elaborate on it.

**Comment by Oozaru71** [comment]
Regarding point 2: Currently the way the application is set up when the app searches for the views it goes "../Views/Home/..." or "..Views/Shared/..." hence why all the cshtml have been placed only under home. The app only searches for folders inside views called home or shared. While this could certainly be changed, it seems easier to simply add the views under home and organize them under folders there.

**Comment by Alejandro-HUB** [comment]
@Oozaru71 Ok, no problem for step 2. Hmm, what about just changing Home's folder name to Alody which is the app's name? Good job for steps 1-3! I looked at your changes and they're working well 👍 I will approve your pull request once you finish points 4-6.

**Comment by Oozaru71** [comment]
@Alejandro-HUB  One question regarding the settings page. In the original muzilla the profile and settings were essentially the same. The user was able to both see hirs profile and to edit it from one page. Would you like for Alody to work the same way or must the profile be separate from the settings? Usually, most apps combine them on the profile page and then for the settings page they add the customization of actual app settings like font, display, or other background settings while the profile page is what allows you to change profile functions like email, uname, and password.

**Comment by Alejandro-HUB** [comment]
@Oozaru71 Good point, but what do you think if we do implement it in a brand new settings page and the page has tabs? Something like Github right? Like when you go into settings you see General, Collaborations, Moderation Options, etc... In this case, we want a tab called profile? If it's too difficult to implement then just do a brand new simple settings page to edit username and password like Muszilla.

Github example: 
<img width="559" alt="image" src="https://user-images.githubusercontent.com/58063303/174419116-a627b9a1-ad12-417b-b804-1c1db14c0727.png">
